### ISSUE TITLE
Statuscolors: Unable to set background color

### ISSUE THREAD

**Issue by jtsmith20158** [jgrar/dwm-patches#5]
Background color of text is always the same as `colors[0][2]` in `config.h`

**Comment by jgrar** [comment]
Hi @jtsmith20158, thanks for testing this patch and bringing this issue to my attention. I can confirm this issue and I'm looking into it.

**Comment by SethBarberee** [comment]
Any progress on this? I can only get the normal color and selected colors of my array to work but the third in my array only changes the foreground and not the background like the OP said

**Comment by jgrar** [comment]
Hi @SethBarberee, I've been really busy with school and haven't had the time to fix it. I'm pretty sure the problem is that I neglected to redraw the box on color change. I can work on it sparingly throughout the rest of the week.

**Comment by jgrar** [comment]
That should do it, let me know if it there's any further trouble.

**Comment by SethBarberee** [comment]
Ok, I'll test it out! Thanks!

On Tue, Apr 19, 2016 at 9:52 AM, Jonathen Russell notifications@github.com
wrote:

> That should do it, let me know if it there's any further trouble.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/jgrar/dwm-patches/issues/5#issuecomment-211961319

## 

Yours in Brotherhood,
Seth Barberee
Penateka Lodge Vice Chief of Service

**Comment by SethBarberee** [comment]
Yeah, it works! Thanks!

**Comment by jgrar** [comment]
@SethBarberee that's good to hear. Just having a thought; could you try it with a leading color that has a different background color than the normal? That is, if your second color scheme has a different background color than the first could you set your status to `"\x2..."` or something like that?

I would do this my self but I reverted my statuscolors test build last night and it will take a while to set up again. But if you can confirm that it draws the bg color across the whole box consistently that would be great.

Edit:
Nevermind, I checked it out and confirmed that it doesn't draw the specified bg color from the beginning of the status box area. This is due to the text being padded on the boundary and the initial fill color set to normal. So if you specify something else at the beginning of the status text the padding area will fill with the normal bg color, not the user's. My bad, i'll work something out.

**Comment by SethBarberee** [comment]
Sure, I'll give it a shot
